version: '3.8'
    
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      #- "8080:8080"  # Don't do this in production!
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro    
    labels:
      # This label for setting router in traefik
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.haikaru.com`)"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080" 
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certResolver=production"
    
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # This label for setting router in traefik
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.haikaru.com`)"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" 
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certResolver=production"

volumes:
  portainer_data:
    external: true
    name: portainer_data
