#docker run -d --hostname rabbitmq --name myrabbit -p 5672:5672 -p 15672:15672 -v rabbitmqdata:/var/lib/rabbitmq rabbitmq:latest

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: myrabbit
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmqdata:
    external: true
    name: rabbitmqdata
