#  docker run -d -p 8000:8000 -p 9000:9000 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock 
#  -v portainer_data:/data portainer/portainer-ce:latest

version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: myportainer
    command: -H unix:///var/run/docker.sock
    restart: always
    port:
      - 9000:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer-ce:latest
    labels:
      # This label for setting router in traefik
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.haikaru.com`)"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" 
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certResolver=production"
